
version: ${project.version}
main: net.drapuria.framework.bukkit.plugin.DrapuriaStandalonePlugin
author: Drapuria Development Team
load: STARTUP
api-version: 1.19
softdepend:
  - ProtocolLib
  - HeadDatabase